### PR TITLE
Fix the folder hierarchy problem in v12 and remove a deprecation warning

### PR DESCRIPTION
**Pull request by matt-duffy**
In v12 the folder hierarchy is not created properly, this PR fixes that, it also removes 1 deprecation warning, marks it as verified in v12 and bumps the version.

I tested it on my vault all works fine but I don't use some features such as merging.

### CODE REVIEW

**Comment by matt-duffy** [comment]
Do you think you might include this PR at some point?

**Comment by roblally** [comment]
> Do you think you might include this PR at some point?

With no response in a ocuple of months, might you consider forking the module at this point @matt-duffy ?

**Comment by matt-duffy** [comment]
> > Do you think you might include this PR at some point?
> 
> With no response in a couple of months, might you consider forking the module at this point @matt-duffy ?

Sure, here is my work, release 3.1.1 is the one I am using in my v12 setup at the moment and it works fine for me:

https://github.com/matt-duffy/lava-flow/

Hopefully the PR will get back into this repo at some point as well.

**Comment by roblally** [comment]
> https://github.com/matt-duffy/lava-flow/

Thank you. I hope it does get merged in.

The original author created something awesome and I am grateful to both of you.

**Comment by DaGwann** [comment]
There an issue in the main project addressing a major issue with the module regarding editing the journal entries created when importing the vault notes. https://github.com/Praxxian/lava-flow/issues/64

Could this issue be solved in this fork, since the original project? Thank you for the fork, by the way. This module is great and hopefully it can be completely functional again.

The issue as posted by 4everGM:

Noticed that any changes I make in Foundry are not saved, but only for journals that were imported from Obsidian. It looks like I can edit/save if I set the sheet configuration to Markdown. I don't believe it behaved this way before, THINKING it is a v12 issue. A warning error in the console shows this:

image

Trying:
Host(s): both Forge and Sqyre
Version V12 Build 331
System: All I've tested.

**Comment by matt-duffy** [comment]
I'm not too sure what is going on here, that deprecation warning is fixed in this fork, but the save does fail if you use the standard journal entry editor, annoyingly no error/warning is thrown.

I don't believe that the module interacts with the save process at all, so I think it must be something to do with the way the journal page is being generated by the import process, as I can add a new page to the journal and modify that fine. 

It might take me a while to work oit what is going on here.

**Comment by matt-duffy** [comment]
> I'm not too sure what is going on here, that deprecation warning is fixed in this fork, but the save does fail if you use the standard journal entry editor, annoyingly no error/warning is thrown.
> 
> I don't believe that the module interacts with the save process at all, so I think it must be something to do with the way the journal page is being generated by the import process, as I can add a new page to the journal and modify that fine.
> 
> It might take me a while to work oit what is going on here.

In fact I have just tested this in base foundry and I think it is working as expected and not to do with Obsidian/LavaFlow.

If you create a journal page and initially set the content using the markdown editor then it is saved as markdown.  You then have to use the markdown editor, you can't use the standard editor.  This makes sense to me as otherwise Foundry would have to convert the HTML generated in the normal editor back into markdown when you save.

So I don't think this is an issue with this module.

To re-create:

1. Start a foundry world using the DND 4.x system
2. Don't add any modules
3. Create a new Journal
4. Add a page to the journal, immediately switch to the markdown editor
5. Add some text and save
6. Edit and change some text in the markdown editor, save
7. See that the changes have been applied
8. Edit again and switch to the dedault text editor, make a change and save
9. See that the changes have **not** been applied

**Comment by DaGwann** [comment]
I see. I guess it makes sense that Foundry behaves like that yes, but it also makes certain things more difficult. Thanks for looking into this!

I was looking to import my Obsidian notes for characters, locations and so on, and from there export those journal entries into compendiums, using Scene Packer to relink the new compendium entries properly. But that module can't edit these entries, since they're markdown. I'll contact that author and see what can be done. Thanks for the help!

**Comment by Praxxian** [comment]
@matt-duffy thank you for your contributions! I am going to include these and some other stuff to resolve v12 compatibility, but I have that in a different branch. I am also going to create a major release to keep it consistent with Foundry's major releases and because the permission change is not backwards compatible.

**Pull request closed without merging**
